### ISSUE TITLE
libcvd impede to run PTAM

### ISSUE THREAD

**Issue by clod85** [ethz-asl/ethzasl_ptam#18]
I'm trying to run ethzasl_ptam framework on a Ubuntu 12.04 machine, ATI graphic video card, ROS groovy.

Once installed I couldn't run ptam node. The message received is:

ERROR: cannot launch node of type [ptam/ptam]: can't locate node [ptam] in package [ptam]

I realized that maybe I have some problems compiling libcvd. After typing rosdep install ptam(or even the command "./configure" and the "make" inside libcvd folder) I get this message:

g++ -o progs/se3_exp progs/se3_exp.o -L. -lcvd  -ltiff -ljpeg -lpng -lpng -llapack -lGLU -lGL -lrt -ldc1394  -L -lX11 -lXext -pthread
./libcvd.so: error: undefined reference to 'raw1394_new_handle'
./libcvd.so: error: undefined reference to 'raw1394_get_port_info'
./libcvd.so: error: undefined reference to 'raw1394_new_handle_on_port'
./libcvd.so: error: undefined reference to 'raw1394_iso_stop'
./libcvd.so: error: undefined reference to 'raw1394_iso_shutdown'
./libcvd.so: error: undefined reference to 'raw1394_reset_bus'
./libcvd.so: error: undefined reference to 'raw1394_destroy_handle'
./libcvd.so: error: undefined reference to 'XUnmapWindow'
./libcvd.so: error: undefined reference to 'XDestroyWindow'
./libcvd.so: error: undefined reference to 'XFlush'
./libcvd.so: error: undefined reference to 'XCloseDisplay'
./libcvd.so: error: undefined reference to 'XStoreName'
./libcvd.so: error: undefined reference to 'XSelectInput'
./libcvd.so: error: undefined reference to 'XNextEvent'
./libcvd.so: error: undefined reference to 'XPending'
./libcvd.so: error: undefined reference to 'XQueryPointer'
./libcvd.so: error: undefined reference to 'XOpenDisplay'
./libcvd.so: error: undefined reference to 'XCreateColormap'
./libcvd.so: error: undefined reference to 'XCreateWindow'
./libcvd.so: error: undefined reference to 'XMapWindow'
./libcvd.so: error: undefined reference to 'XGetWindowAttributes'
./libcvd.so: error: undefined reference to 'XSetClassHint'
./libcvd.so: error: undefined reference to 'XInternAtom'
./libcvd.so: error: undefined reference to 'XSetWMProtocols'
./libcvd.so: error: undefined reference to 'XLoadQueryFont'
./libcvd.so: error: undefined reference to 'XCreateGlyphCursor'
./libcvd.so: error: undefined reference to 'XFreeFont'
./libcvd.so: error: undefined reference to 'XResizeWindow'
./libcvd.so: error: undefined reference to 'XMoveWindow'
./libcvd.so: error: undefined reference to 'XWarpPointer'
./libcvd.so: error: undefined reference to 'XDefineCursor'
./libcvd.so: error: undefined reference to 'XUndefineCursor'
./libcvd.so: error: undefined reference to 'XLookupString'
./libcvd.so: error: undefined reference to 'png_set_longjmp_fn'
collect2: ld returned 1 exit status
make: **\* [progs/se3_exp] Error 1

I've already read here:

http://stackoverflow.com/questions/16077809/libcvd-undefined-reference-to-x-while-compiling-c

that is a known problem on the MakeFile but I can't fix it.

Does PTAM node not run because of this problem? Or is the ATI graphic card that doesn't allow me to execute the node correctly?

I even try to download libcvd from ethzasl 's git repository and from Edward Rosten's website but I still can't fix the problem. Thank you very much

**Comment by Ziyou1987** [comment]
I had the same error : [tcsetpgrp failed in terminal_inferior: Inappropriate ioctl for device]
could you tell me how you changed the launch file ?

so I've modified line 2 of launch files in this way:

and finally it works.
I can not see that line between these two lines.
