### ISSUE TITLE
PtamParamsConfig.h missing

### ISSUE THREAD

**Issue by stefangachter** [ethz-asl/ethzasl_ptam#39]
I am trying to build the package with `catkin_make` but end up with the following error:

```
[ 23%] Building CXX object ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o
In file included from /home/gstef/catkin_ws/src/ethzasl_ptam/ptam/src/CameraCalibrator.cc:5:0:
/home/gstef/catkin_ws/src/ethzasl_ptam/ptam/include/ptam/Params.h:11:35: fatal error: ptam/PtamParamsConfig.h: No such file or directory
compilation terminated.
make[2]: *** [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o] Error 1
make[1]: *** [ethzasl_ptam/ptam/CMakeFiles/cameracalibrator.dir/all] Error 2
make: *** [all] Error 2
Invoking "make" failed
```

I cannot find the file `PtamParamsConfig.h` and I do not know how to generate it. Could somebody point out how to proceed? Any help will be apprecaited.

**Comment by acajic** [comment]
I have the same issue. 

```
[ 81%] Building CXX object ethzasl_ptam-master/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o
In file included from /home/andrija/ros_packages/src/ethzasl_ptam-master/ptam/src/CameraCalibrator.cc:5:0:
/home/andrija/ros_packages/src/ethzasl_ptam-master/ptam/include/ptam/Params.h:11:35: fatal error: ptam/PtamParamsConfig.h: No such file or directory
 #include <ptam/PtamParamsConfig.h>
                               ^
compilation terminated.
make[2]: *** [ethzasl_ptam-master/ptam/CMakeFiles/cameracalibrator.dir/src/CameraCalibrator.cc.o] Error 1
make[1]: *** [ethzasl_ptam-master/ptam/CMakeFiles/cameracalibrator.dir/all] Error 2
make: *** [all] Error 2
```

Only I am not able to find the `PtamParamsConfig.h` anywhere in the downloaded repository.

**Comment by aspears1935** [comment]
The solution in my case is below:

The dependency PtamParamsConfig.h file wasn't being generated before packages that needed it were being built. To solve this I called catkin_make for just the config file generator node before calling catkin_make again to make all packages. i.e.:
- >> catkin_make ptam_gencfg 
- >> catkin_make

Doing it in this order guaranteed that the PtamParamsConfig.h file was generated before it was required to build the main ptam nodes. 

So I found that for a successful clean build in Ubuntu 14.04 follow these steps:
- Install Ubuntu 14.04
- Install ros-indigo-desktop-full (http://wiki.ros.org/indigo/Installation/Ubuntu)
- Install PTAM dependencies: >> sudo apt-get install git libblas-dev liblapack-dev freeglut3-dev
- Create catkin_ws: >> mkdir -p ~/catkin_ws/src
- Clone the ptam project into the src directory
- Navigate to catkin_ws dir >> cd catkin_ws
- **Make the config files >> catkin_make ptam_gencfg**
- Make the ptam project >> catkin_make 

Hopefully that helps some others as well.
